import os
import cv2
import torch
import numpy as np
import torch.nn as nn
import matplotlib.pyplot as plt
from PIL import Image
import torchvision.models as models
import torchvision.transforms as transforms
from transformers import pipeline

# 1. Pipeline Initialization Context
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# LOCAL PATH: Target your local fine-tuned model folder path
SEGFORMER_PATH = "busi-cllassifisification/final_busi_segformer_model"
segmenter = pipeline(task='image-segmentation', model=SEGFORMER_PATH)
# Your explicit custom MobileNetV3 architecture class definition
class BUSIMobilenet(nn.Module):
    def __init__(self, num_classes: int):
        super(BUSIMobilenet, self).__init__()
        base_model = models.mobilenet_v3_small(weights=None) # Set weights to None since we load custom checkpoint
        in_features = 576
        self.model = nn.Sequential(
            base_model.features,
            base_model.avgpool,
            nn.Flatten(),
            nn.Linear(in_features, 256),
            nn.Hardswish(),
            nn.Dropout(0.3, inplace=True),
            nn.Linear(256, num_classes)
        )
    
    def forward(self, x):
        return self.model(x)

# Initialize your explicit model class structure for 3 diagnostic classes
classifier_model = BUSIMobilenet(num_classes=3)

# LOCAL PATH: Target your local checkpoint file path
CLASSIFIER_WEIGHTS_PATH = "busi-cllassifisification/checkpoints/best_mobilenetv3_busi.pth"
classifier_model.load_state_dict(torch.load(CLASSIFIER_WEIGHTS_PATH, map_location=DEVICE))
classifier_model.to(DEVICE)
classifier_model.eval()

CLASSIFIER_CLASSES = {0: "Benign", 1: "Malignant", 2: "Normal"}

classifier_transforms = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

# 2. Transparent Core Blending Processor
def overlay_mask_transparent_memory(pil_image, pil_mask, alpha=0.4):
    img = cv2.cvtColor(np.array(pil_image.convert("RGB")), cv2.COLOR_RGB2BGR)
    mask = np.array(pil_mask.convert("L"))
    
    if img.shape[:2] != mask.shape:
        mask = cv2.resize(mask, (img.shape[1], img.shape[0]), interpolation=cv2.INTER_NEAREST)
    
    color_overlay = np.zeros_like(img)
    color_overlay[:] = [0, 0, 255] 
    
    output = img.copy()
    num_pixels = mask > 0
    output[num_pixels] = cv2.addWeighted(img, 1 - alpha, color_overlay, alpha, 0)[num_pixels]
    
    return Image.fromarray(cv2.cvtColor(output, cv2.COLOR_BGR2RGB))

# 3. Master Execution Routine
def run_breast_cancer_diagnosis(image_path, alpha=0.4):
    # --- Load Image Asset ---
    original_img = Image.open(image_path)
    
    # --- Step A: Custom BUSIMobilenet Classification ---
    input_tensor = classifier_transforms(original_img.convert("RGB")).unsqueeze(0).to(DEVICE)
    with torch.no_grad():
        outputs = classifier_model(input_tensor)
        probabilities = torch.nn.functional.softmax(outputs, dim=1)[0]
        predicted_class_idx = torch.argmax(probabilities).item()
        
    predicted_label = CLASSIFIER_CLASSES[predicted_class_idx]
    confidence_score = probabilities[predicted_class_idx].item() * 100
    
    # --- Step B: Segformer Lesion Segmentation ---
    results = segmenter(original_img)
    
    tumor_mask = None
    for entity in results:
        if entity['label'] == 'tumor':
            tumor_mask = entity['mask']
            break

    if tumor_mask is None and len(results) > 0:
        tumor_mask = results[0]['mask']

    if tumor_mask is None:
        raise ValueError("No segmentation mask was generated by the model.")

    mask_array = np.array(tumor_mask)
    
    # --- Step C: Generate Blended Vision Output ---
    fused_visualization = overlay_mask_transparent_memory(original_img, tumor_mask, alpha=alpha)
    fused_visualization.save("lesion_overlay_transparent.png")
    
    # --- Step D: Construct and Output Visual Summary ---
    fig, axes = plt.subplots(1, 3, figsize=(15, 5))

    axes[0].imshow(original_img, cmap='gray')
    axes[0].set_title("1. Original Ultrasound")
    axes[0].axis('off')

    axes[1].imshow(mask_array, cmap='gray')
    axes[1].set_title("2. Predicted Tumor Mask")
    axes[1].axis('off')

    axes[2].imshow(fused_visualization)
    axes[2].set_title(f"3. Diagnosis: {predicted_label} ({confidence_score:.2f}%)")
    axes[2].axis('off')

    plt.tight_layout()
    plt.show()
    
    return {
        "status": predicted_label,
        "confidence": confidence_score,
        "overlay_image": fused_visualization,
        "mask_array": mask_array
    }

# --- Execution Entry Point ---
analysis_results = run_breast_cancer_diagnosis(
    image_path="busi-cllassifisification/data/BUSI/malignant/malignant (1).png"
)
